:memo: Move installation and example commands into separate pages (#47)
* :truck: Move API reference and Changelog links to top-level navigation

Xref https://mystmd.org/guide/website-navigation#navigation-header

* :truck: Move installation instructions from main README to docs/index.md

* :rewind: Revert "Move API ref and Changelog links to top-level nav"

This reverts commit e032c935272a77f941b2d082f5472079dfa7d967. The navigation links are placed under a 'User Guide' section.

* :truck: Move Rust ndarray and dlpack examples to src/lib.rs

Putting Rust code examples in a place that will show up on docs.rs later. Have edited the text to describe how the CogReader method outputs to DLPack and read_geotiff function outputs to ndarray::Array3. Also making the python module non-public (they weren't really exposed in Rust), and pointing to the Python docs on readthedocs.

* :memo: Document errors section for read_geotiff function

Only mentioning the `IoError: Data type mismatch` possibility for now.

* :truck: Move Python examples to new Quickstart page

Move example NumPy and Xarray code from main README.md to docs/quickstart.md. The new page contains a table showing three methods of reading GeoTIFFs into different Python objects, notably the new PyCapsule (DLPack) method.

* :memo: Recategorize sections in API Reference based on output type

Rename 'Classes' to 'DLPack', and 'Functions' to 'NumPy'. Added a new 'Xarray' section to document Cog3pioBackendEntrypoint, and included an example doctest too. Note the lack of a `:members:` directive for the xarray backend class, because of an `AttributeError: 'MySTNodeVisitor' object has no attribute 'visit_abbreviation'. Did you mean: 'visit_admonition'?` error.

* :pencil2: Typo quickstart.md -> quickstart.html

* :bulb: Update roadmap for rest of 2025 to 2026

Planning for the initial release to crates.io and PyPI by the end of this quarter, then will focus on GPU-based decoding via nvTIFF, and potentially refactoring to use async-tiff. Long-term goal is still direct-to-GPU loading!