:mute: Disable Rust nightly tests
Due to`error[E0080]: unable to determine layout for `<<T as PyClassImpl>::BaseType as PyClassBaseType>::LayoutAsBase` because `<<T as PyClassImpl>::BaseType as PyClassBaseType>::LayoutAsBase` cannot be normalized
 --> /rustc/f37aa9955f03bb1bc6fe08670cb1ecae534b5815/library/core/src/mem/mod.rs:1247:26
  |
  = note: evaluation of `<pycell::impl_::PyClassObject<T> as std::mem::SizedTypeProperties>::ALIGN` failed here`.