:memo: Recategorize sections in API Reference based on output type
Rename 'Classes' to 'DLPack', and 'Functions' to 'NumPy'. Added a new 'Xarray' section to document Cog3pioBackendEntrypoint, and included an example doctest too. Note the lack of a `:members:` directive for the xarray backend class, because of an `AttributeError: 'MySTNodeVisitor' object has no attribute 'visit_abbreviation'. Did you mean: 'visit_admonition'?` error.