:arrow_up: Bump pyo3 from 0.21.1 to 0.22.4, numpy from 0.21.0 to 0.22.0 (#19)
* :arrow_up: Bump pyo3 from 0.21.1 to 0.22.4, numpy from 0.21.0 to 0.22.0

Bumps [pyo3](https://github.com/pyo3/pyo3) from 0.21.1 to 0.22.4.
- [Release notes](https://github.com/pyo3/pyo3/releases)
- [Changelog](https://github.com/PyO3/pyo3/blob/main/CHANGELOG.md)
- [Commits](https://github.com/pyo3/pyo3/compare/v0.21.1...v0.22.4)

Bumps [numpy](https://github.com/PyO3/rust-numpy) from 0.21.0 to 0.22.0.
- [Release notes](https://github.com/PyO3/rust-numpy/releases)
- [Changelog](https://github.com/PyO3/rust-numpy/blob/main/CHANGELOG.md)
- [Commits](https://github.com/PyO3/rust-numpy/compare/v0.21.0...v0.22.0)

* :alien: Import pyo3::types::PyModuleMethods

Needed to fix `error[E0599]: no method named `add_class` found for reference `&pyo3::Bound<'_, PyModule>` in the current scope` and `error[E0599]: no method named `add_function` found for reference `&pyo3::Bound<'_, PyModule>` in the current scope`.