:alien: Import pyo3::types::PyModuleMethods
Needed to fix `error[E0599]: no method named `add_class` found for reference `&pyo3::Bound<'_, PyModule>` in the current scope` and `error[E0599]: no method named `add_function` found for reference `&pyo3::Bound<'_, PyModule>` in the current scope`.