:boom: Read into CUDA memory DLPack tensor (#57)
* :arrow_up: Bump cudarc from 0.16.6 to 0.17.3

Bumps [cudarc](https://github.com/coreylowman/cudarc) from 0.16.6 to 0.17.3.
- [Release notes](https://github.com/coreylowman/cudarc/releases)
- [Commits](https://github.com/coreylowman/cudarc/compare/v0.16.6...v0.17.3)

* :arrow_up: Bump dlpark from 0.6.0 to d6c7e17 with cuda feature

Bumps [dlpark](https://github.com/SunDoge/dlpark) from 0.6.0 to d6c7e17.
- [Release notes](https://github.com/SunDoge/dlpark/releases)
- [Changelog](https://github.com/SunDoge/dlpark/blob/main/CHANGELOG.md)
- [Commits](https://github.com/SunDoge/dlpark/compare/v0.6.0...d6c7e17e911a4a0ff80f3c010370e15dd3ac683c)

* :recycle: Refactor to_cuda method to dlpack method

Put CudaSlice<u8> into a DLPack tensor via a dlpack() method, towards having a similar API with the non-cuda image-tiff backend. Limitation of current implementation is that DLPack tensor is in bytes (u8), and a flattened 1D shape (i.e. not a 3D tensor).

* :triangular_flag_on_post: Remove dlpark/cuda from default features

Can't enable dlpark's 'cuda' feature by default, need to hide it behind cog3pio's 'cuda' feature flag.

* :heavy_plus_sign: Add rstest

Fixture-based test framework for Rust!

* :sparkles: Transmute CudaSlice to proper dtype before entering DLPack

Handle conversion from u8 to other dtypes before putting data into DLPack. Need to determine dtype from sample_format and bits_per_pixel. Transmute turns CudaSlice into CudaView, so need https://github.com/SunDoge/dlpark/pull/29 for dlpark to support conversion to DLPack from CudaView. Also had to bump up opt-level from 1 (basic optimizations) to 2 (some optimizations), because `nvtiffDecodeCheckSupported` is failing with `NVTIFF_STATUS_TIFF_NOT_SUPPORTED (4)` on test/dev builds again.

Note to self that transmute is likely happening on native endian? Need to check that little/big endian TIFFs are properly decoded later.

* :white_check_mark: Add tests for reading u8/u16/u32/i16/i32 tiffs

Bunch of parametrized tests to ensure that reading various uint/int dtype TIFFs work. The u64/i64 TIFFs from GDAL's test suite are not supported by nvTIFF yet for some reason though.

* :memo: Document CudaCogReader usage in src/lib.rs

Split the page into CPU and GPU sections. Add example on how to read a TIFF file using object_store, set up a cudarc::CudaStream, and pass those into CudaCogReader, then call `.dlpack()` to get a DLPack tensor. Also corrected docstring on `CudaCogReader::dlpack()` method and changed `doc_auto_cfg` -> `doc_cfg`.

* :truck: Move CudaCogReader dlpack example to src/io/nvtiff.rs

Retain CPU-only code in src/lib.rs, but move the 'cuda' feature-gated example to src/io/nvtiff.rs. There are workarounds to keep things on the main page, but decided that it looks better to have it closer to the struct documentation anyway.

* :mute: Disable Rust nightly tests

Due to`error[E0080]: unable to determine layout for `<<T as PyClassImpl>::BaseType as PyClassBaseType>::LayoutAsBase` because `<<T as PyClassImpl>::BaseType as PyClassBaseType>::LayoutAsBase` cannot be normalized
 --> /rustc/f37aa9955f03bb1bc6fe08670cb1ecae534b5815/library/core/src/mem/mod.rs:1247:26
  |
  = note: evaluation of `<pycell::impl_::PyClassObject<T> as std::mem::SizedTypeProperties>::ALIGN` failed here`.

* :goal_net: Remove some unwraps and improve unimplemented docs

Raise NvTiffStatusError where possible, or a slightly helpful message for unimplemented branches. Document that f16 and complex dtypes and certain compression types may not be supported yet.