:label: Generate pyi stub files for type hints (#72)
* :heavy_plus_sign: Add pyo3-stub-gen and pyo3-stub-gen-derive

Stub file (*.pyi) generator for PyO3! Crates at https://crates.io/crates/pyo3-stub-gen and https://crates.io/crates/pyo3-stub-gen-derive

* :hammer: Create python stub file generator script

Xref https://github.com/Jij-Inc/pyo3-stub-gen/tree/0.19.0?tab=readme-ov-file#generate-a-stub-file. Also need to bump MSRV from 1.85.0 to 1.91.0 to fix complain about macro `gen_stub_pyclass` and `gen_stub_pymethods` having some "item is stable in a `const` context since `1.91.0`".

* :arrow_up: Bump MSRV from 1.85.0 to 1.91.0

To satisfy `gen_stub_pyclass` and `gen_stub_pymethods` macros.

* :green_heart: Add missing pyo3 feature flag

To fix `error[E0433]: failed to resolve: could not find `python` in the crate root`.

* :construction_worker: Add mypy stubtest CI check

Validate that stub files match runtime behaviour. Xref https://github.com/Jij-Inc/pyo3-stub-gen/tree/0.19.0?tab=readme-ov-file#advanced-mypystubtest-integration and https://mypy.readthedocs.io/en/stable/stubtest.html#automatic-stub-testing-stubtest

* :label: Fix or ignore some type hint errors

Mostly in the xarray_backend.py file. Also added unit test to check cog3pio.__doc__ attribute, and sneaked in a small addition to .release-plz.toml

* :green_heart: Type hint returned DLPack tensor as types.PyCapsule

Fix `error: Argument 1 to "from_dlpack" has incompatible type "CogReader"; expected "_SupportsDLPack[None]"  [arg-type]` by properly setting return type from __dlpack__ method as types.CapsuleType. Also need to add stream parameter to satisfy numpy.from_dlpack, xref https://github.com/numpy/numpy/blob/v2.4.2/numpy/__init__.pyi#L1075-L1077

* :label: Generate type stubs for CudaCogReader

Finalize type hint generation for the cog3pio API surface. Needed to reorganize feature gates a bit to make `pyo3` flag mandatory for type stub generation, while `cuda` remains optional. Also fixed an incorrect intersphinx type hint in src/python/adapters.rs.

* :memo: Parse :label: under Documentation section in changelog

* :beers: Run stubtest with cuda feature enabled

To fix `error: cog3pio.CudaCogReader is not present at runtime`

* :mute: Silence clippy error about unused variable: `kwargs`

dl_device will be handled in #71, copy another time.