:construction_worker: Track Rust performance benchmarks on CI (#61)
* :arrow_up: Bump criterion from 0.5.1 to 0.7.0

Bumps [criterion](https://github.com/bheisler/criterion.rs) from 0.5.1 to 0.7.0.
- [Changelog](https://github.com/bheisler/criterion.rs/blob/master/CHANGELOG.md)
- [Commits](https://github.com/bheisler/criterion.rs/compare/0.5.1...0.7.0)

No need to use the criterion.rs fork set at f07ae721237c5ab107d0b5429f8fa349cd16a072/#27, because the original error `assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())` can been fixed by setting nresamples to 2, yeah I know right!

* :construction_worker: Run criterion benchmarks on CI with cargo-codspeed

Use codspeed-criterion-compat crate inplace of criterion, and setup CI job to run the Rust benchmarks!

* :green_heart: Run on ghcr.io/osgeo/gdal:ubuntu-small-3.11.5 container

And bump to georust/gdal version with GDAL 3.11 bindings.

* :rotating_light: Set git config core.longpaths to true

Fix `failed to update submodule `gdal-src/source` ... Caused by: path too long: 'C:/Users/runneradmin/.cargo/git/checkouts/gdal-3b51095beae5b4fc/3df2c28/gdal-src/source/...`.

* :green_heart: Cargo remove gdal-src and gdal-sys in benchmark tests

Fix `undefined reference to `GDALGetRasterBand'` and various other linker errors. Just rely on existing GDAL installation within the docker container, rather than the pre-built bindings.

* :alembic: Benchmark with LiberTIFF driver

Benchmark reading with GDAL 3.11's LiberTIFF driver, using 4 threads. Also renumbered the benchmark IDs to start from 0.

* :egg: Do host to device copy when 'cuda' flag is enabled

Ensure fair comparison between nvTIFF which reads to CUDA memory (even though it's the fastest already), and the GDAL LiberTIFF and image-tiff backend readers.